parse_config:
  raw_binding_map:
    'DE_A_UMLAUT': 'MY_A_UMLAUT'
    'DE_U_UMLAUT': 'MY_U_UMLAUT'
    'DE_O_UMLAUT': 'MY_O_UMLAUT'
    'DE_SHARP_S': 'MY_SHARP_S'
    'DE_Y': 'MY_Y'
    'DE_Z': 'MY_Z'
    'DE_EURO': 'MY_EURO'
    'DE_HASH': 'MY_HASH'
    'DE_STAR': 'MY_STAR'
    'DE_PLUS': 'MY_PLUS'
    'DE_DEG': 'MY_DEG'
    'DE_EQUAL': 'MY_EQUAL'
    'DE_SEMI': 'MY_SEMI'
    'DE_LPAR': 'MY_LPAR'
    'DE_RPAR': 'MY_RPAR'
    'DE_CARET': 'MY_CARET'
    'DE_DLLR': 'MY_DLLR'
    'DE_BSLH': 'MY_BSLH'
    'DE_FSLH': 'MY_FSLH'
    'DE_MINUS': 'MY_MINUS'
    'DE_SECT': 'MY_SECT'
    'DE_AMPS': 'MY_AMPS'
    'DE_LBRC': 'MY_LBRC'
    'DE_RBRC': 'MY_RBRC'
    'DE_PRCNT': 'MY_PRCNT'
    'DE_GRAVE': 'MY_GRAVE'
    'DE_ACUTE': 'MY_ACUTE'
    'DE_EXCL': 'MY_EXCL'
    'DE_QMARK': 'MY_QMARK'
    'DE_UNDER': 'MY_UNDER'
    'DE_COLON': 'MY_COLON'
    'DE_AT': 'MY_AT'
    'DE_TILDE': 'MY_TILDE'
    'DE_PIPE': 'MY_PIPE'
    'DE_LBKT': 'MY_LBKT'
    'DE_RBKT': 'MY_RBKT'
    'DE_GT': 'MY_GT'
    'DE_LT': 'MY_LT'
    'DE_COMMA': 'MY_COMMA'
    'DE_SQT': 'MY_SQT'
    'DE_DOT': 'MY_DOT'

  zmk_keycode_map:
    # Home row mappings (Base/MIR)
    A: {t: "A", type: "homerow"}
    I: {t: "I", type: "homerow"}
    E: {t: "E", type: "homerow"}
    N: {t: "N", type: "homerow"}
    C: {t: "C", type: "homerow"}
    T: {t: "T", type: "homerow"}
    R: {t: "R", type: "homerow"}
    S: {t: "S", type: "homerow"}
    
    # Home row mappings (SYM) using the bypassed MACRO names
    MY_EQUAL: {t: "=", type: "homerow"}
    MY_SEMI: {t: ";", type: "homerow"}
    MY_LPAR: {t: "(", type: "homerow"}
    MY_RPAR: {t: ")", type: "homerow"}
    MY_QMARK: {t: "?", type: "homerow"}
    MY_UNDER: {t: "_", type: "homerow"}
    MY_COLON: {t: ":", type: "homerow"}
    MY_AT: {t: "@", type: "homerow"}

    # Home row mappings (NUM)
    N0: {t: "0", type: "homerow"}
    N3: {t: "3", type: "homerow"}
    N2: {t: "2", type: "homerow"}
    N1: {t: "1", type: "homerow"}

    # Home row mappings (NAV)
    LEFT: {t: "←", type: "homerow"}
    DOWN: {t: "↓", type: "homerow"}
    RIGHT: {t: "→", type: "homerow"}
    F5: {t: "F5", type: "homerow"}
    F6: {t: "F6", type: "homerow"}
    F7: {t: "F7", type: "homerow"}
    F8: {t: "F8", type: "homerow"}

    # Home row mappings (SYS)
    BT_SEL 0: {t: "BT 0", type: "homerow"}
    BT_SEL 1: {t: "BT 1", type: "homerow"}
    BT_SEL 2: {t: "BT 2", type: "homerow"}
    BT_SEL 3: {t: "BT 3", type: "homerow"}
    RGB_SAI: {t: "SAI", type: "homerow"}
    RGB_BRI: {t: "BRI", type: "homerow"}
    RGB_SPI: {t: "SPI", type: "homerow"}
    RGB_EFF: {t: "EFF", type: "homerow"}

    # Standard mappings bypassing the DE_ macros
    MY_A_UMLAUT: Ä
    MY_U_UMLAUT: Ü
    MY_O_UMLAUT: Ö
    MY_SHARP_S: ß
    MY_Y: Y
    MY_Z: Z
    MY_EURO: "€"
    MY_HASH: "#"
    MY_STAR: "*"
    MY_PLUS: "+"
    MY_DEG: "°"
    MY_CARET: "^"
    MY_DLLR: "$"
    MY_BSLH: "\\"
    MY_FSLH: "/"
    MY_MINUS: "-"
    MY_SECT: "§"
    MY_AMPS: "&"
    MY_LBRC: "{"
    MY_RBRC: "}"
    MY_PRCNT: "%"
    MY_GRAVE: "`"
    MY_ACUTE: "´"
    MY_EXCL: "!"
    MY_TILDE: "~"
    MY_PIPE: "|"
    MY_LBKT: "["
    MY_RBKT: "]"
    MY_GT: ">"
    MY_LT: "<"
    MY_COMMA: ","
    MY_SQT: "'"
    MY_DOT: "."
    
    # Base Modifiers and Keys
    LEFT_ALT: "⌥"
    LCTRL: "⌃"
    LSHFT: "⇧"
    LGUI: "❖"
    ESC: "⎋"
    DEL: "⌦"
    ENTER: "⏎"
    BACKSPACE: "⌫"
    SPACE: "␣"
    TAB: "⇥"
    UP: "↑"
    PRINTSCREEN: "⎙"

    # Macros
    LC(S): "⌃S"
    LC(DE_Z): "⌃Z"
    LC(DE_Y): "⌃Y"
    LC(LA(LG(C))): "Crop"
    LC(F): "⌃F"
    LG(DE_DOT): "Emoji"
    LC(A): "⌃A"
    LC(X): "⌃X"
    LC(C): "⌃C"
    LC(V): "⌃V"
    BT_CLR: "BT CLR"
    BT_SEL: "BT"
    RGB_TOG: "RGB TG"
    RGB_COLOR_HSB(0,100,50): "RED"
    RGB_COLOR_HSB(126,100,50): "GRN"
    RGB_COLOR_HSB(244,100,50): "BLU"
    RGB_COLOR_HSB(309,100,50): "PUR"
    RGB_COLOR_HSB(61,100,50): "YEL"
  
  zmk_combos: {}
  mark_alternate_layer_activators: true

draw_config:
  svg_extra_style: |
    text {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;
      font-size: 25px !important;
    }
    g.key rect {
      fill: #e2e8f0 !important;
      stroke: #64748b !important;
    }
    g.trans rect {
      fill: none !important;
      stroke-dasharray: 4;
    }
    g.homerow rect {
      fill: #ffffff !important;
      stroke: #475569 !important;
    }
