name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "config/keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: ""

  convert_to_png:
    needs: draw
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libcairo2
          pip install keymap-drawer cairosvg
      - name: Generate Vertical SVG and Convert to PNG
        run: |
          sed -i 's/n_columns: 3/n_columns: 1/g' config/keymap_drawer.config.yaml
          for yaml_file in keymap-drawer/*.yaml; do
            base_name=$(basename "$yaml_file" .yaml)
            keymap -c config/keymap_drawer.config.yaml draw -j config/info.json "$yaml_file" > "keymap-drawer/${base_name}_vertical.svg"
            cairosvg -b white --output-width 1200 -o "keymap-drawer/${base_name}.png" "keymap-drawer/${base_name}_vertical.svg"
          done
      - name: Commit PNGs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add keymap-drawer/*.png
          git add keymap-drawer/*_vertical.svg
          git commit -m "Convert keymap SVGs to PNGs" || exit 0
          git push
